name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  format-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Format Markdown with markdownlint
        run: |
          npm install -g markdownlint-cli
          markdownlint --disable MD013 --fix . --ignore CODE_OF_CONDUCT.md
          git add -A
          git diff --cached --exit-code
